global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-microservices'
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ['product-service:8087', 'order-service:8087', 'customer-service:8080', 'inventory-service:8087', 'payment-service:8087']

