global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-microservices'
    static_configs:
      - targets: ['product-service:8080', 'order-service:8080', 'customer-service:8080', 'inventory-service:8080', 'payment-service:8080']
